from tasky.prompts import Classified, classify, make_title, parse_notifications, queue_request


def test_classify_plain_prompt_is_task():
    assert classify("refactor the login flow") == Classified(
        kind="task", text="refactor the login flow"
    )


def test_classify_empty_text_is_ignored():
    assert classify("").kind == "ignore"


def test_classify_whitespace_only_text_is_ignored():
    assert classify("   \n  ").kind == "ignore"


def test_classify_slash_command_with_args_is_task():
    text = (
        "<command-message>review</command-message>\n"
        "<command-name>/review</command-name>\n"
        "<command-args>the payment module</command-args>"
    )
    result = classify(text)
    assert result.kind == "task"
    assert result.text == "/review the payment module"


def test_classify_slash_command_without_args_is_ignored():
    text = (
        "<command-message>review</command-message>\n"
        "<command-name>/review</command-name>\n"
        "<command-args></command-args>"
    )
    assert classify(text).kind == "ignore"


def test_classify_slash_command_missing_args_tag_is_ignored():
    text = "<command-message>review</command-message>\n<command-name>/review</command-name>"
    assert classify(text).kind == "ignore"


def test_classify_task_notification_is_notification():
    text = "<task-notification>\n<task-id>ab12</task-id>\n</task-notification>"
    result = classify(text)
    assert result.kind == "notification"
    assert result.text == text


def test_classify_local_command_output_is_ignored():
    assert classify("<local-command-stdout>ok</local-command-stdout>").kind == "ignore"


def test_classify_caveat_is_ignored():
    assert classify("Caveat: the messages below were generated by a tool").kind == "ignore"


def test_classify_system_reminder_is_ignored():
    assert classify("<system-reminder>context</system-reminder>").kind == "ignore"


def test_classify_bash_tags_are_ignored():
    assert classify("<bash-input>ls</bash-input>").kind == "ignore"
    assert classify("<bash-stdout>ok</bash-stdout>").kind == "ignore"
    assert classify("<bash-stderr>fail</bash-stderr>").kind == "ignore"


def test_classify_interrupted_request_is_ignored():
    assert classify("[Request interrupted by user]").kind == "ignore"


def test_parse_notifications_single_block():
    text = (
        "<task-notification>\n"
        "<task-id>ab12</task-id>\n"
        "<tool-use-id>toolu_x</tool-use-id>\n"
        "<output-file>/tmp/x.output</output-file>\n"
        "<status>completed</status>\n"
        '<summary>Agent "X" finished</summary>\n'
        "<result>four</result>\n"
        "</task-notification>"
    )
    assert parse_notifications(text) == [
        {"task_id": "ab12", "tool_use_id": "toolu_x", "status": "completed", "result": "four"}
    ]


def test_parse_notifications_multiple_blocks():
    block = (
        "<task-notification>\n<task-id>{tid}</task-id>\n<tool-use-id>{tool}</tool-use-id>\n"
        "<status>completed</status>\n<result>{res}</result>\n</task-notification>"
    )
    text = block.format(tid="a1", tool="t1", res="one") + "\n" + block.format(
        tid="a2", tool="t2", res="two"
    )
    result = parse_notifications(text)
    assert [n["task_id"] for n in result] == ["a1", "a2"]
    assert [n["result"] for n in result] == ["one", "two"]


def test_parse_notifications_missing_tags_are_none():
    text = "<task-notification>\n<task-id>ab12</task-id>\n</task-notification>"
    assert parse_notifications(text) == [
        {"task_id": "ab12", "tool_use_id": None, "status": None, "result": None}
    ]


def test_parse_notifications_no_blocks_returns_empty_list():
    assert parse_notifications("just a normal prompt") == []


def test_queue_request_not_prefixed_returns_none():
    assert queue_request("write the migration", "++") is None


def test_queue_request_prefix_only_returns_empty_string():
    assert queue_request("++", "++") == ""
    assert queue_request("++   ", "++") == ""


def test_queue_request_prefixed_text_returns_stripped_body():
    text = "++ write the migration for invoices"
    assert queue_request(text, "++") == "write the migration for invoices"


def test_make_title_uses_first_non_empty_line():
    text = "\n\n  first real line  \nsecond line"
    assert make_title(text) == "first real line"


def test_make_title_collapses_internal_whitespace():
    assert make_title("do   the\tthing\n now") == "do the thing"


def test_make_title_truncates_with_ellipsis():
    title = make_title("a" * 200, limit=20)
    assert len(title) == 20
    assert title.endswith("…")


def test_make_title_returns_empty_for_blank_text():
    assert make_title("   \n  \n") == ""
